version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/node"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/php"
    schedule:
      interval: "daily"
