name: Create package Node
 
on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'node/**'

jobs:
  create_node_package_and_push:
    name: Create Node package and push
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        run: |
          git checkout main

      - name: Zip Node archive
        run: |
           zip -r node.zip node

      - name: Push Node Zip to packages branch
        run: |
          git checkout packages
          git add node.zip
          git commit -m "Added new PHP package: '${{ github.event.head_commit.message }}'"
          git push
          
  