name: Create releases
 
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

    branches:
      - 'main'

jobs:
  create-artifacts:
    name: Create artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload Node artifact
        uses: actions/upload-artifact@v3
        with:
          name: node-artifact
          path: node

      - name: Upload PHP artifact
        uses: actions/upload-artifact@v3
        with:
          name: php-artifact
          path: php


  create-release:
    name: Create release
    needs: create-artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clean workspace
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Download node artifact
        uses: actions/download-artifact@v3
        with:
          name: node-artifact
          path: node

      - name: Archive Node
        uses: thedoctor0/zip-release@0.7.0
        with:
          path: node
          type: 'zip'
          filename: 'node.zip'

      - name: Download php artifact
        uses: actions/download-artifact@v3
        with:
          name: php-artifact
          path: php

      - name: Archive PHP
        uses: thedoctor0/zip-release@0.7.0
        with:
          path: php
          type: 'zip'
          filename: 'php.zip'

      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: ${{ github.repository }}
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create Node release
        uses: ncipollo/release-action@v1
        with:
          artifacts: node.zip, php.zip
          tag: samples
          name: samples