name: main
 
on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - closed

    branches:
      - 'main'

jobs:
  create-node-artifact:
    name: Create Node artifact
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Node files changed check
        id: node-files
        uses: tj-actions/changed-files@v35
        with:
          files: node/**

      - name: Upload Node artifact
        if: steps.node-files.outputs.any_changed == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: node
          path: node   

      - name: Check exist zip file
        if: steps.node-files.outputs.any_changed == 'false'
        run: |
          echo "No files modified"
          exit 1

  create-node-release:
    name: Create Node release
    needs: create-node-artifact
    if: |
      always() && 
      !contains(needs.*.result, 'failure')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download node artifact
        if: steps.node-files.outputs.any_changed == 'true'
        id: download
        uses: actions/download-artifact@v3
        with:
          name: node
          path: node

      - name: Archive Release
        if: steps.node-files.outputs.any_changed == 'true'
        uses: thedoctor0/zip-release@0.7.0
        with:
          type: 'zip'
          path: node
          filename: 'node.zip'

      - name: Create Node release
        uses: ncipollo/release-action@v1
        with:
          artifacts: node.zip
          tag: node-v${{ github.run_number }}
          name: node-v${{ github.run_number }}
          makeLatest: true