name: main

on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - closed

    branches:
      - 'main'

jobs:
  create-node-release:
    name: Release Node
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Node files changed check
        id: node-files
        uses: tj-actions/changed-files@v35
        with:
          files: node/**

      - name: Upload Node artifact if exist files changed
        if: steps.node-files.outputs.any_changed == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: node
          path: node   

      - name: Download node artifact
        if: steps.node-files.outputs.any_changed == 'true'
        uses: actions/download-artifact@v3
        with:
          name: node

      - name: Create Node release
        uses: ncipollo/release-action@v1
        with:
          artifacts: node
          tag: node-v${{ github.run_number }}